### ISSUE TITLE
EventDrop example does work

### ISSUE THREAD

**Issue by sttoussaint** [hoonzis/KoExtensions#1]
Hi,
I have tried to use your "enhanced event drop" chart but I only have the text "Last Week Sales:". I have used the html file from your testpages directory.
Can you tell me what is wrong?
Thank you.
Stephan

**Comment by hoonzis** [comment]
Hi,

Thnx for reporting this. The script files were not correctly loaded by require, so non of the charts was working. It's fixed now.
